version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: ms-reporte-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: reporte_db
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:


